- name: INSTALL CERTBOT
  yum:
    name: certbot
    enablerepo: "rhui-REGION-rhel-server-extras,rhui-REGION-rhel-server-optional"

#https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html
- name: TURN OFF TOWER
  shell: ansible-tower-service stop

#If this fails check out status of certbot: https://letsencrypt.status.io/
- name: ISSUE CERT
  shell: certbot certonly --standalone -d {{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}} --email ansible-network@redhat.com --noninteractive --agree-tos
  register: issue_cert
  until: issue_cert is not failed
  retries: 5
  ignore_errors: yes

- name: APPEND LETS ENCRYPT FAILED
  set_fact:
    dns_information: |
      - The Lets Encrypt certbot failed, please check https://letsencrypt.status.io/ to make sure the service is running
  run_once: yes
  delegate_to: localhost
  delegate_facts: true
  when: issue_cert is failed

- name: debug this for sean
  debug:
    msg: "{{dns_information}}"

- name: MOVE SSL KEY
  copy:
    remote_src: True
    src: "/etc/letsencrypt/live/{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/privkey.pem"
    dest: /etc/tower/tower.key
  when: issue_cert is not failed

- name: MOVE SSL CERT
  copy:
    remote_src: True
    src: "/etc/letsencrypt/live/{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/cert.pem"
    dest: /etc/tower/tower.cert
  when: issue_cert is not failed

# THIS IS LOCATED HERE
# https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
- name: MOVE INTERMEDIATE CERT
  copy:
    src: "lets-encrypt-x3-cross-signed.pem.txt"
    dest: "/usr/share/pki/ca-trust-source/anchors/lets-encrypt-x3-cross-signed.pem.txt"

- name: LOAD INTERMEDIATE CERT
  shell: update-ca-trust

- name: TURN ON TOWER
  shell: ansible-tower-service start

- name: CHANGE TOWER BASE URL
  tower_settings:
    name: TOWER_URL_BASE
    value: "https://{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    tower_verify_ssl: no
    tower_host: localhost
    tower_username: admin
    tower_password: "{{admin_password}}"
